

services:
  mongo_db:
    image: mongo:7.0 
    container_name: play-history-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  app:
    build:
      context: . 
      target: development
    container_name: play-history-service
    ports:
      - 3000:3000 
    depends_on:
      - mongo_db # Ensure DB starts before the app tries to connect
    environment:
      MONGODB_URI: mongodb://mongo_db:27017/play_history_db
      PORT: 3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules  

volumes:
  mongo_data:
  node_modules: 

