
services:
  mongodb-test:
    image: mongo:7
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_DATABASE: playevents_test
    tmpfs:
      - /data/db  # Use in-memory storage for faster tests
    networks:
      - test-network

networks:
  test-network:
    driver: bridge